### ISSUE TITLE
Full web2code dataset release inquiry

### ISSUE THREAD

**Issue by namezhenzhang** [MBZUAI-LLM/web2code#3]
Dear authors,

I read your paper and found it insightful. I'm interested in experimenting with your web2code dataset, but noticed only 100 samples are available on Hugging Face. I was wondering if you have plans to release the full dataset, and if so, could you share any information about the potential timeline?

Thank you for your time and contribution to the field.

**Comment by namezhenzhang** [comment]
Sorry I notice I can download them from [Files and versions] hh.
I will close this issue.

**Comment by xiaoxiaoye218** [comment]
Hello, I still haven't found it. Could you please tell me where I can find it?
